package com.example.todolist.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class TodoModel(
    var title: String,
    var description: String,
    var category: String,
    var date: Long,
    var time: Long,
    var isFinished: Int = 0,
    @PrimaryKey(autoGenerate = true)
    var id: Long = 0// Here we've added id as last parameter, because in kotlin we have named
    // arguments so when we make an object of this class, we'll have to pass id if it
    // is the first parameter. And, since primary kill will be autogenerated, we don't
    // want to pass it every time we make an object of this class. So, instead of making
    // it first parameter, we make it last
)
